name: 🎥 Nova Aula/Vídeo
description: Propor uma nova aula ou vídeo para o módulo
title: "[AULA] "
labels: ["enhancement", "content", "video"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🎥 Proposta de Nova Aula/Vídeo
        
        Obrigado por contribuir com uma proposta de novo conteúdo! 
        Por favor, preencha as informações abaixo para ajudar na avaliação.

  - type: dropdown
    id: submodulo
    attributes:
      label: Submódulo
      description: Em qual submódulo esta aula se encaixa?
      options:
        - "6.1 - Papéis e Carreira em Dados"
        - "6.2 - Metodologias Ágeis para Dados"
        - "6.3 - Gestão de Projetos de Dados"
        - "6.4 - Liderança de Equipes de Dados"
        - "6.5 - Cultura Data-Driven"
      default: 0
    validations:
      required: true

  - type: input
    id: titulo
    attributes:
      label: Título da Aula
      description: Título proposto para a aula
      placeholder: "Ex: Gestão de Stakeholders em Projetos de ML"
    validations:
      required: true

  - type: input
    id: duracao
    attributes:
      label: Duração Estimada
      description: Duração estimada da aula (em minutos)
      placeholder: "Ex: 45min"
    validations:
      required: true

  - type: textarea
    id: objetivos
    attributes:
      label: Objetivos de Aprendizagem
      description: Quais são os principais objetivos de aprendizagem desta aula?
      placeholder: |
        - Objetivo 1: Compreender...
        - Objetivo 2: Aplicar...
        - Objetivo 3: Analisar...
    validations:
      required: true

  - type: textarea
    id: conteudo
    attributes:
      label: Conteúdo Principal
      description: Descreva o conteúdo que será abordado na aula
      placeholder: |
        - Tópico 1: ...
        - Tópico 2: ...
        - Tópico 3: ...
    validations:
      required: true

  - type: textarea
    id: prerequisitos
    attributes:
      label: Pré-requisitos
      description: Quais conhecimentos prévios são necessários?
      placeholder: |
        - Conhecimento básico de...
        - Experiência com...
    validations:
      required: false

  - type: textarea
    id: recursos
    attributes:
      label: Recursos Adicionais
      description: Quais recursos adicionais seriam úteis? (slides, templates, cases, etc.)
      placeholder: |
        - Template de...
        - Case prático sobre...
    validations:
      required: false

  - type: checkboxes
    id: formato
    attributes:
      label: Formato Sugerido
      description: Qual formato seria mais adequado?
      options:
        - label: Videoaula expositiva
        - label: Demo prático / hands-on
        - label: Case study / análise de caso
        - label: Entrevista com especialista
        - label: Workshop interativo

  - type: textarea
    id: justificativa
    attributes:
      label: Justificativa
      description: Por que este conteúdo é importante para o módulo?
      placeholder: |
        Este conteúdo é importante porque...
    validations:
      required: true

  - type: textarea
    id: contexto
    attributes:
      label: Contexto Adicional
      description: Alguma informação adicional relevante?
      placeholder: |
        Referências, links úteis, exemplos...
    validations:
      required: false
